import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Headers';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head></head>

            <body>
                {/* <Providers> */}
                <div
                    className={
                        // cn(
                        'flex h-screen w-screen text-sm lg:text-base'
                        // ,inter.className,
                        // )
                    }
                >
                    {/* <Sidebar /> */}
                    <div className="flex flex-1 flex-col">
                        <Header />
                        <div className="flex flex-1 flex-col overflow-y-auto">
                            <main className="flex-1">{children}</main>
                            {/* <Footer /> */}
                        </div>
                    </div>
                </div>
                {/* </Providers> */}
            </body>
        </html>
    );
}
